openapi: 3.1.1
info:
  title: Auth Service - User API
  version: 1.0.0

paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './user-schemas.yml#/components/schemas/UserDto'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: './user-schemas.yml#/components/schemas/UserDto'
        '400':
          description: Invalid input
