openapi: 3.1.1
info:
  title: Auth Service - User API
  version: 1.0.0

paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './user-schemas.yml#/components/schemas/UserDto'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: './user-schemas.yml#/components/schemas/UserDto'
        '400':
          description: Invalid input

  /users/{uuid}:
    get:
      operationId: fetchUserById
      summary: Fetches a user by its id.
      parameters:
        - $ref: "../common/common-schema.yml#/components/parameters/path_uuid"
      responses:
        "200":
          description: User with specified id successfully fetched.
          content:
            application/json:
              schema:
                $ref: './user-schemas.yml#/components/schemas/UserDto'
        "404":
          description: User not found
